os: linux
dist: trusty

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

jobs:
  include:
    - script:
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
