name: deploy

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
            persist-credentials: false

        - name: Install dependencies
          run: npm ci

        - name: Build project
          run: npm run build --if-present --prod

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@3.6.2
          with:
              GIT_CONFIG_NAME: Github Actions
              GIT_CONFIG_EMAIL: git@foxtrotfanatics.com
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages
              FOLDER: dist/website
              COMMIT_MESSAGE: Deploy website to GH-Pages
