name: Unit/Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Unit/Integration Tests

    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]
        node-version: [10.13, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build:
    name: Building to `prod` branch

    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - name: Configure git credentials
      run: |
        git config --global user.email "hello@foxtrotfanatics.com"
        git config --global user.name "Foxtrot Fanatics"
    - run: git checkout -B prod
    - run: npm run-script build
    - name: Exclude non-prod content
      run: |
        FILES=$(ls -I Dockerfile -I dist)
        rm -rf $FILES
        mv dist/website/* .
        rm -rf dist
    - run: git add -A
    - run: git commit -am "Website Build"
    - name: Delete prod if already exists
      run: |
        if [[ -n "$(git ls-remote --heads origin prod)" ]]; then
          git push origin --delete prod
        fi
    - run: git push origin prod
