name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Unit/Integration Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.X

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    # - name: Run unit tests
    #   run: npm test
