name: unit-tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
            persist-credentials: false

        - name: Install dependencies
          run: npm ci

        - name: Build project
          run: npm run build --if-present --prod
